### ISSUE TITLE
Corrupting dfnstation.cfg file

### ISSUE THREAD

**Issue by hdevillepoix** [ScottDay/DFN-Maintenance-GUI-Backend#6]
`updateConfigFile` is appending to file lat/lon values, instead of updating it.
Should use config parser module.
`save_config_file` in dfn_functions.py for example.

**Comment by MartinCupak** [comment]
looks like the modification of parameters in dfnstation.cfg does ignore sections.
example: lon is in both [clouds] and [station] sections, both lon parameters are changed, but the only one 
to be changed - lon(gitude) - is the one in [station]. 'lon' in [clouds] must stay unchanged.
_Note: [clouds]->lon is related to cloudiness detection algorithm and may break 
down the cloudiness detection functionality_
